### ISSUE TITLE
Missing community guidelines

### ISSUE THREAD

**Issue by olivecha** [METHODS-Group/DRDMannTurb#101]
Please add a paragraph in the `README` describing:

*"Clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support"*

**Comment by mjachi** [comment]
Hi, I made a quick update to our README with a contributions and questions section and added templates for issues and feature requests. Please confirm the changes and we can close the issue.

**Comment by olivecha** [comment]
This is perfect thanks!
