### ISSUE TITLE
[FEATURE] [JOSS] Consider using conda-lock

### ISSUE THREAD

**Issue by HaoZeke** [METHODS-Group/DRDMannTurb#115]
**Problem you'd like to address**
I noticed that #99 deals with version mismanagement between operating systems, perhaps `conda-lock` [1] might be of assistance here.

[1] https://github.com/conda/conda-lock

**Propose your solution**
Like any `lockfile` approach, `conda-lock` pins versions for later, the main difference is that new dependencies are explicitly resolved against the standard operating systems by default.

**Additional context**
Not really part of the JOSS review [2], but came up as part of it.

[2] https://github.com/openjournals/joss-reviews/issues/6838

**Comment by mjachi** [comment]
Thank you for the suggestion! I added conda-lock in #127 and have updated the README. Let us know if you have any other thoughts on this or happen to catch any issues.

**Comment by HaoZeke** [comment]
Excellent, closing 

> Thank you for the suggestion! I added conda-lock in #127 and have updated the README. Let us know if you have any other thoughts on this or happen to catch any issues.
