### ISSUE TITLE
[JOSS] Missing reference

### ISSUE THREAD

**Issue by HaoZeke** [METHODS-Group/DRDMannTurb#116]
**Description**
@editorialbot notes a missing reference: https://github.com/openjournals/joss-reviews/issues/6838#issuecomment-2295423711

**Reproduction/Minimal Working Example**
`@editorialbot check references`

**Expected behavior**
Should be clean. I believe the cannonical reference style here would be to either cite the version of the code closest to the publication most used (by the authors) from this list: https://www.hawc2.dk/hawc2-publications

Or (less fair TBH) to use the latest and the first publication references.

**Environment information**
N/A

**Additional context**
Final [JOSS tasks](https://github.com/openjournals/joss-reviews/issues/6838).

**Comment by mjachi** [comment]
I've just updated the citation. It seems that the HAWC2 authors/DTU affiliates just reference the HAWC2 user manual in their publications, except the user manual is not published. We opted to cite their [most recent journal publication](https://wes.copernicus.org/articles/5/1/2020/#section2) they have listed there.

**Comment by HaoZeke** [comment]
> I've just updated the citation. It seems that the HAWC2 authors/DTU affiliates just reference the HAWC2 user manual in their publications, except the user manual is not published. We opted to cite their [most recent journal publication](https://wes.copernicus.org/articles/5/1/2020/#section2) they have listed there.

SGTM, thanks
