### ISSUE TITLE
[JOSS] Benchmark results

### ISSUE THREAD

**Issue by HaoZeke** [METHODS-Group/DRDMannTurb#118]
In particular, I note that the paper currently includes the line(s):

```
Once calibrated, a DRD model is no more expensive for simulating turbulence than a Mann model.
```

However, this should be borne out in a sample study / benchmark, and I'd assume there were reasonable limits to this (i.e. no unreasonably large number of parameters).

This could also be closed by just reframing the sentence a bit, perhaps something like, ".. has a good expense to cost ratio compared to a Mann model and is significantly more general" ? 

Part of https://github.com/openjournals/joss-reviews/issues/6838

**Comment by mjachi** [comment]
We decided to just remove this line altogether.

**Comment by HaoZeke** [comment]
> We decided to just remove this line altogether, if that is fine?

Works for me.
