### ISSUE TITLE
[JOSS Review] Typo in references 

### ISSUE THREAD

**Issue by paroomk** [METHODS-Group/DRDMannTurb#98]
1. Please fix the typo in the last reference listed in the JOSS paper (DOI link). 
2. Also, please provide the reference for HAWC2 mentioned in line 42 of the paper. 

cf: [JOSS-6838](https://github.com/openjournals/joss-reviews/issues/6838)

**Comment by alizma** [comment]
Hi @paroomk, thank you for the comments. I updated the references and recompiled the article on our submission. Please confirm the changes so I can close the issue.

**Comment by paroomk** [comment]
Hi @alizma, references look good now. Thanks!
